workflows:
  default-workflow:
    name: Default Workflow
    environment:
      vars:
        CM_USE_AUTOMATIC_SIGNING: "true" # 使用 Codemagic 的自動簽名功能
    scripts:
      - name: Fetch dependencies
        script: flutter pub get
      - name: Build iOS app
        script: flutter build ios --release --no-codesign
    artifacts:
      - build/ios/ipa/**/*.ipa